### ISSUE TITLE
Example on homepage fails with `unreachable`

### ISSUE THREAD

**Issue by kurtbuilds** [devashishdxt/rexie#42] opened 2023-10-22 18:04 UTC
I'm trying to get the README code to work, but it fails with an unreachable error. Here's a full `lib.rs`:

```rs
use rexie::*;
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

pub type JsResult<T = JsValue> = std::result::Result<T, JsError>;

async fn build_database() -> Result<Rexie> {
    // Create a new database
    let rexie = Rexie::builder("test")
        // Set the version of the database to 1.0
        .version(1)
        // Add an object store named `employees`
        .add_object_store(
            ObjectStore::new("employees")
                // Set the key path to `id`
                .key_path("id")
                // Enable auto increment
                .auto_increment(true)
                // Add an index named `email` with the key path `email` with unique enabled
                .add_index(Index::new("email", "email").unique(true)),
        )
        // Build the database
        .build()
        .await?;

    // Check basic details of the database
    assert_eq!(rexie.name(), "test");
    assert_eq!(rexie.version(), 1.0);
    assert_eq!(rexie.store_names(), vec!["employees"]);

    Ok(rexie)
}

static EMPLOYEE_STORE: &str = "employees";

async fn add_employee(rexie: &Rexie, name: &str, email: &str) -> Result<u32> {
    // Create a new read-write transaction
    let transaction = rexie.transaction(&[EMPLOYEE_STORE], TransactionMode::ReadWrite)?;

    // Get the `employees` store
    let employees = transaction.store(EMPLOYEE_STORE)?;

    // Create an employee
    let employee = serde_json::json!({
        "name": name,
        "email": email,
    });
    // Convert it to `JsValue`
    let employee = serde_wasm_bindgen::to_value(&employee).unwrap();

    // Add the employee to the store
    let employee_id = employees.add(&employee, None).await?;

    // Waits for the transaction to complete
    transaction.done().await?;

    // Return the employee id
    let id = employee_id.as_f64().unwrap() as u32;
    Ok(id)
}

async fn get_employee(rexie: &Rexie, id: u32) -> Result<Option<serde_json::Value>> {
    // Create a new read-only transaction
    let transaction = rexie.transaction(&[EMPLOYEE_STORE], TransactionMode::ReadOnly)?;

    // Get the `employees` store
    let employees = transaction.store(EMPLOYEE_STORE)?;

    // Get the employee
    let employee = employees.get(&id.into()).await?;
    // Next two lines are commented out, as they're not README code. But this actually works, whereas README code does not. See below.
    // let employee: serde_json::Value = employee.into_serde().unwrap();
    // let employee = Some(employee);

    let employee: Option<serde_json::Value> = serde_wasm_bindgen::from_value(employee).unwrap();

    // Return the employee
    Ok(employee)
}

#[wasm_bindgen]
pub async fn hello() -> JsResult {
    let rex = build_database().await?;
    let id = add_employee(&rex, "John Doe", "john@test.com").await?;
    log(&format!("id: {}", id));
    let employee = get_employee(&rex, id).await?;
    // Ok(JsValue::from_str("Hello, world!"))
    let employee = serde_wasm_bindgen::to_value(&employee).unwrap();
    Ok(employee)
}
```

Cargo.toml

```toml
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.87", features = ["serde-serialize"] }
js-sys = "0.3.64"
wasm-bindgen-futures = "0.4.37"
rexie = "0.5.0"
serde-wasm-bindgen = "0.6.0"
serde_json = "1.0.107"
serde = { version = "1.0.189", features = ["derive"] }

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
]
```

When I run the code in a frontend application, I get this error: ```sync_wasm_bg.wasm:0x16288 Uncaught (in promise) RuntimeError: unreachable```.

The unreachable line is somewhere within the line: ```let employee: Option<serde_json::Value> = serde_wasm_bindgen::from_value(employee).unwrap();```. Interestingly, if I use the now-deprecated `into_serde()` method on JsValue, the code works. Use the commented out code next to the comment "Get the employee":

```rs
    // Get the employee
    let employee = employees.get(&id.into()).await?;
    let employee: serde_json::Value = employee.into_serde().unwrap();
    let employee = Some(employee);
```

I'm not sure if this error is rooted in rexie or with serde_wasm_bindgen, but seems related to serde_wasm_bindgen deserializing an object from indexed db. If I make up an JSON object from a static str, serde_wasm_bindgen does handle it correctly, so I think it's specifically how serde_wasm_bindgen handles indexeddb objects. But since that library is used in the README, I'm assuming there's some iteration of it where this works.

**Comment by FlippingBinary** [comment] 2024-01-07 00:41
Perhaps there was a change in `serde_wasm_bindgen`? It works if you get it as a `HashMap`.

```rs
async fn get_employee(rexie: &Rexie, id: u32) -> Result<HashMap<String,String>> {
    // Create a new read-only transaction
    let transaction = rexie.transaction(&[EMPLOYEE_STORE], TransactionMode::ReadOnly)?;

    // Get the `employees` store
    let employees = transaction.store(EMPLOYEE_STORE)?;

    // Get the employee
    let employee = employees.get(&id.into()).await?;

    // Convert to a HashMap
    let employee:HashMap<String,String> = serde_wasm_bindgen::from_value(employee).unwrap();

    // Return the employee
    Ok(employee)
}
```

The type error was revealed by using the `console_error_panic_hook` crate.

```rs
#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
}
```

**Comment by devashishdxt** [comment] 2024-01-07 03:27
I think there's some issue with deserialising in `serde_wasm_bindgen`. Here's a simple example which does not involve any database operations fail:

```rust
let employee: serde_json::Value = serde_json::json!({
    "name": "My Name",
    "email": "email@google.com",
});

// Convert it to `JsValue`
let serialized = serde_wasm_bindgen::to_value(&employee).unwrap();

// Convert back to `Value`
let deserialized: serde_json::Value = serde_wasm_bindgen::from_value(serialized).unwrap();

assert_eq!(employee, deserialized);
```

**Comment by devashishdxt** [comment] 2024-01-07 03:30
Closing this issue as the issue is not related to `rexie`. Please re-open if there are any actionable items for this repository.

**Closed by devashishdxt** 2024-01-07 03:30 UTC

**Comment by FlippingBinary** [comment] 2024-01-09 23:27
I think this was just a documentation issue. The documentation in the `README.md` demonstrates a usage that will not build.

This line fails:

https://github.com/devashishdxt/rexie/blob/c6bce1961d101b74b92a01e87f128cbfafa43655/README.md?plain=1#L96

But it could be changed to:

```rs
let employee: HashMap<String,String> = serde_wasm_bindgen::from_value(employee).unwrap();
```

And it will build as long as the return value of `get_employee` is also adjusted.
