### ISSUE TITLE
TransactionInactiveError

### ISSUE THREAD

**Issue by anlumo** [devashishdxt/rexie#36] opened 2023-01-24 18:33 UTC
I have code that tries to read/modify/write entries in a table. It basically looks like this:

```rust
async fn modify(ids: &[Uuid]) {
    let transaction = database.transaction(&["foo"], TransactionMode::ReadWrite)?;
    let table = transaction.store("foo")?;
    for id in ids {
        let obj = table.get(&id.to_string()).await?;
        // modify object here
        table.put(&obj, None).await?;
    }
    transaction.done().await?;
}
```

This code results in the error `failed to execute indexed db request: TransactionInactiveError: Failed to execute 'put' on 'IDBObjectStore': The transaction is not active.`

My research ([source](https://stackoverflow.com/a/33092002)) indicates that the transaction is inactive right when control is given back to the JS event loop and active again only in the callback of the IndexedDB operation (the `get` in this case).

This is inherently incompatible with the way async/await works in Rust, since you don't get control to exactly when the Future is polled (only that it won't happen before the operation finishes).

I don't quite get how others get this to work, since this doesn't seem to be such an uncommon operation to do, and I can't find any hints of problems reported by others over this?

This was tested on Chromium 108.

I've now moved to using the `idb-sys` crate that doesn't use async, and there it works fine. The code is just way more convoluted, unfortunately.

**Comment by devashishdxt** [comment] 2023-01-31 06:23
> I've now moved to using the `idb-sys` crate that doesn't use async, and there it works fine. The code is just way more convoluted, unfortunately.

Thanks for creating this issue. Can you also try with `idb` crate which uses `async/await` syntax?

**Comment by devashishdxt** [comment] 2023-02-01 03:24
I've added tests in `idb` crate to test this and it seems to work: https://github.com/devashishdxt/idb/blob/750d6d3a3e4c2e0a0e0c821c853e5e8b1db8d0c0/idb/tests/transaction.rs#L167

**Comment by anlumo** [comment] 2023-02-01 03:26
I suspect that if there's no Future to process other than the idb one, it's always going to bounce to that one when the transaction is active again, making this impossible to test in isolation. You'd have to schedule something else at the same time that's not the same IndexedDB transaction.

**Comment by devashishdxt** [comment] 2023-02-01 03:33
Can you provide an example of what you're trying to do in `// modify object here`?

**Comment by anlumo** [comment] 2023-02-01 03:35
I'm recording the last access date, so I'm updating the timestamp there.

**Comment by devashishdxt** [comment] 2023-02-01 03:41
It is not possible for me to debug this without a reproducible example.

**Comment by anlumo** [comment] 2023-02-01 03:42
I'll try to come up with something.

**Comment by elsirion** [comment] 2023-08-28 19:51
I ran int the same issue and was able to reproduce the problem in your `idb` test suite by adding some sleeps:

```
panicked at 'id should be ok: failed to add a value: TransactionInactiveError: Failed to execute 'add' on 'IDBObjectStore': The transaction has finished.', idb/tests/transaction.rs:199:9
```

* [Test run failure](https://github.com/elsirion/idb/actions/runs/6004230427/job/16284360042#step:6:161)
* [Patch to reproduce](https://github.com/elsirion/idb/pull/1/commits/f828a2da4dc769ffc800c604fd8679635a8d455d)

If anyone else in this thread found a solution since then please lmk, I'm contemplating building my own transaction system on top :scream:

**Comment by devashishdxt** [comment] 2023-08-29 01:33
@elsirion Thanks for sharing an example. IndexedDB transaction work a little different as compared to transactions in other databases. Any transaction with no outstanding request gets committed when the control of event loop is given back to the browser. In your example, `sleep` returns the control of event loop to the browser and as there aren't any more pending requests on transaction, it is auto-committed.

If you want long-lived transaction across the event-loop control boundaries, you'll have to add some logic to do that yourself.

Making a network call is another example of surrendering the control of event loop to the browser. So, the transaction may get auto-committed if you make a network call.

Here are some notes on IndexedDB's transaction lifecycle: https://www.w3.org/TR/IndexedDB/#transaction-lifecycle

Here's a potential approach that may be used to handle this: https://jlongster.com/future-sql-web (refer to `Long-lived IndexedDB transactions` section in this article).

**Comment by elsirion** [comment] 2023-08-29 09:51
Yeah, it's not a bug in this crate, just insane semantics of IndexedDB transactions :cry: 

My best bet is probably to build an ACID-compliant transaction abstraction on top and then only use the IndexedDB transactions at commit time so that there are no interruptions in execution.

**Comment by elsirion** [comment] 2023-08-29 13:44
> This ticket is about Rust Futures being inherently incompatible with indexeddb API.

I agree, given the lack of guarantees about rust future execution and the IndexedDB behavior I don't really see how these can be made to work together reliably. It might work by accident most of the time or for limited use cases where rexie futures always return `Ready` on first poll and never yield to the executor, but I'd be very uncomfortable building a bigger application on top.

That's why I think the two problems are related. Having a proper transaction implementation on top of `idb-sys` in Rexie would solve the problem and is likely the only way to do so. Would such a patch be welcome @devashishdxt?

**Comment by devashishdxt** [comment] 2023-08-31 03:44
@elsirion Sure. You can try adding a transaction implementation (like other JS libraries do) on top. I think this'll greatly increase usability of indexedDB transaction in wasm.

**Closed** 2024-07-04 07:51 UTC
